-- ============================================================
-- AI 开发助理模块 Chunk 1 — TBS 物理表资源 + resfield
-- 6 个 TBS 资源: TSS_AIDEV_SESSION/CHANGESET/CHANGEITEM/UPGRADE/UPGRADE_LOG/UPGRADE_SNAPSHOT
-- 铁律: TBS 字段 REFFIELDID=NULL, ID 字段 ISKEY=1 KEYGENTYPE=GUID, RESOURCEANAME='A'
-- ============================================================

-- ============================================================
-- 1. tss_resource — 6 个 TBS 资源
-- ============================================================
INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_session_001', 'TSS_AIDEV_SESSION', 'A', 'tss_aidev_session', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_session_001');

INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_changeset_001', 'TSS_AIDEV_CHANGESET', 'A', 'tss_aidev_changeset', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_changeset_001');

INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_changeitem_001', 'TSS_AIDEV_CHANGEITEM', 'A', 'tss_aidev_changeitem', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_changeitem_001');

INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_upgrade_001', 'TSS_AIDEV_UPGRADE', 'A', 'tss_aidev_upgrade', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_upgrade_001');

INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_upgrade_log_001', 'TSS_AIDEV_UPGRADE_LOG', 'A', 'tss_aidev_upgrade_log', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_upgrade_log_001');

INSERT INTO tss_resource (ID, RESOURCENAME, RESOURCEANAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tss_aidev_upgrade_snapshot_001', 'TSS_AIDEV_UPGRADE_SNAPSHOT', 'A', 'tss_aidev_upgrade_snapshot', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID = 'tss_aidev_upgrade_snapshot_001');

-- ============================================================
-- 2. tss_resfield — TSS_AIDEV_SESSION 字段 (13 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_id', 'tss_aidev_session_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_code', 'tss_aidev_session_001', NULL, 'SESSIONCODE', '会话编码', 'varchar', NULL, 0, 50, '会话编码', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_code');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_name', 'tss_aidev_session_001', NULL, 'SESSIONNAME', '会话名称', 'varchar', NULL, 0, 200, '会话名称', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_name');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_type', 'tss_aidev_session_001', NULL, 'SESSIONTYPE', '会话类型', 'varchar', NULL, 1, 16, '会话类型', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_type');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_tmod', 'tss_aidev_session_001', NULL, 'TARGETMODULE', '目标模块', 'varchar', NULL, 1, 64, '目标模块编码', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_tmod');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_intent', 'tss_aidev_session_001', NULL, 'INTENT', '开发意图', 'text', NULL, 1, 0, '开发意图描述', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_intent');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_status', 'tss_aidev_session_001', NULL, 'STATUS', '状态', 'varchar', NULL, 0, 16, '状态', 0, NULL, 'DRAFT', 7
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_status');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_cby', 'tss_aidev_session_001', NULL, 'CREATEDBY', '创建人', 'varchar', NULL, 1, 36, '创建人ID', 0, NULL, NULL, 8
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_cby');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_ctime', 'tss_aidev_session_001', NULL, 'CREATEDTIME', '创建时间', 'datetime', NULL, 1, 0, '创建时间', 0, NULL, NULL, 9
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_ctime');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_close', 'tss_aidev_session_001', NULL, 'CLOSEDATE', '关闭日期', 'datetime', NULL, 1, 0, '关闭日期', 0, NULL, NULL, 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_close');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_csid', 'tss_aidev_session_001', NULL, 'CHANGESETID', '变更包ID', 'varchar', NULL, 1, 36, '关联变更包ID', 0, NULL, NULL, 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_csid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_remark', 'tss_aidev_session_001', NULL, 'REMARK', '备注', 'varchar', NULL, 1, 500, '备注', 0, NULL, NULL, 12
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_remark');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aisess_isdel', 'tss_aidev_session_001', NULL, 'ISDELETED', '是否删除', 'int', NULL, 0, 1, '是否删除', 0, NULL, '0', 13
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aisess_isdel');

-- ============================================================
-- 3. tss_resfield — TSS_AIDEV_CHANGESET 字段 (11 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_id', 'tss_aidev_changeset_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_sid', 'tss_aidev_changeset_001', NULL, 'SESSIONID', '会话ID', 'varchar', NULL, 0, 36, '会话ID', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_sid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_code', 'tss_aidev_changeset_001', NULL, 'CHANGESETCODE', '变更包编码', 'varchar', NULL, 0, 50, '变更包编码', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_code');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_title', 'tss_aidev_changeset_001', NULL, 'TITLE', '标题', 'varchar', NULL, 1, 200, '标题', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_title');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_src', 'tss_aidev_changeset_001', NULL, 'SOURCE', '来源', 'varchar', NULL, 1, 16, '来源', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_src');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_intent', 'tss_aidev_changeset_001', NULL, 'INTENT', '意图', 'text', NULL, 1, 0, '意图描述', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_intent');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_vp', 'tss_aidev_changeset_001', NULL, 'VALIDATIONPASSED', '校验通过', 'int', NULL, 0, 1, '校验是否通过', 0, NULL, '0', 7
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_vp');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_vr', 'tss_aidev_changeset_001', NULL, 'VALIDATIONREPORT', '校验报告', 'text', NULL, 1, 0, '校验报告', 0, NULL, NULL, 8
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_vr');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_cnt', 'tss_aidev_changeset_001', NULL, 'ITEMCOUNT', '项数量', 'int', NULL, 0, 11, '变更项数量', 0, NULL, '0', 9
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_cnt');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_ctime', 'tss_aidev_changeset_001', NULL, 'CREATEDTIME', '创建时间', 'datetime', NULL, 1, 0, '创建时间', 0, NULL, NULL, 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_ctime');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aics_isdel', 'tss_aidev_changeset_001', NULL, 'ISDELETED', '是否删除', 'int', NULL, 0, 1, '是否删除', 0, NULL, '0', 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aics_isdel');

-- ============================================================
-- 4. tss_resfield — TSS_AIDEV_CHANGEITEM 字段 (17 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_id', 'tss_aidev_changeitem_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_csid', 'tss_aidev_changeitem_001', NULL, 'CHANGESETID', '变更包ID', 'varchar', NULL, 0, 36, '变更包ID', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_csid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_seq', 'tss_aidev_changeitem_001', NULL, 'ITEMSEQ', '项序号', 'int', NULL, 1, 11, '项序号', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_seq');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_cat', 'tss_aidev_changeitem_001', NULL, 'CATEGORY', '类别', 'varchar', NULL, 1, 32, '类别', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_cat');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_act', 'tss_aidev_changeitem_001', NULL, 'ACTION', '操作', 'varchar', NULL, 1, 16, '操作', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_act');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_tool', 'tss_aidev_changeitem_001', NULL, 'TOOL', '工具', 'varchar', NULL, 1, 64, '生成工具', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_tool');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_tgt', 'tss_aidev_changeitem_001', NULL, 'TARGET', '目标', 'varchar', NULL, 1, 128, '目标对象', 0, NULL, NULL, 7
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_tgt');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_sql', 'tss_aidev_changeitem_001', NULL, 'SQLCONTENT', 'SQL内容', 'text', NULL, 1, 0, 'SQL内容', 0, NULL, NULL, 8
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_sql');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_md', 'tss_aidev_changeitem_001', NULL, 'METADATA', '元数据', 'text', NULL, 1, 0, '元数据JSON', 0, NULL, NULL, 9
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_md');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_rat', 'tss_aidev_changeitem_001', NULL, 'RATIONALE', '理由', 'text', NULL, 1, 0, '设计理由', 0, NULL, NULL, 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_rat');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_warn', 'tss_aidev_changeitem_001', NULL, 'WARNINGS', '警告', 'text', NULL, 1, 0, '警告信息', 0, NULL, NULL, 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_warn');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_dep', 'tss_aidev_changeitem_001', NULL, 'DEPENDSON', '依赖项', 'varchar', NULL, 1, 500, '依赖项ID列表', 0, NULL, NULL, 12
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_dep');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_status', 'tss_aidev_changeitem_001', NULL, 'ITEMSTATUS', '项状态', 'varchar', NULL, 0, 16, '项状态', 0, NULL, 'DRAFT', 13
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_status');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_cb', 'tss_aidev_changeitem_001', NULL, 'CONFIRMEDBY', '确认人', 'varchar', NULL, 1, 36, '确认人ID', 0, NULL, NULL, 14
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_cb');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_ctime', 'tss_aidev_changeitem_001', NULL, 'CONFIRMEDTIME', '确认时间', 'datetime', NULL, 1, 0, '确认时间', 0, NULL, NULL, 15
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_ctime');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_corder', 'tss_aidev_changeitem_001', NULL, 'CONFIRMORDER', '确认顺序', 'int', NULL, 1, 11, '确认顺序', 0, NULL, NULL, 16
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_corder');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aici_isdel', 'tss_aidev_changeitem_001', NULL, 'ISDELETED', '是否删除', 'int', NULL, 0, 1, '是否删除', 0, NULL, '0', 17
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aici_isdel');

-- ============================================================
-- 5. tss_resfield — TSS_AIDEV_UPGRADE 字段 (17 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_id', 'tss_aidev_upgrade_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_code', 'tss_aidev_upgrade_001', NULL, 'UPGRADECODE', '升级编码', 'varchar', NULL, 0, 50, '升级编码', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_code');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_scode', 'tss_aidev_upgrade_001', NULL, 'SESSIONCODE', '会话编码', 'varchar', NULL, 1, 50, '会话编码', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_scode');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_sname', 'tss_aidev_upgrade_001', NULL, 'SESSIONNAME', '会话名称', 'varchar', NULL, 1, 200, '会话名称', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_sname');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_stype', 'tss_aidev_upgrade_001', NULL, 'SESSIONTYPE', '会话类型', 'varchar', NULL, 1, 16, '会话类型', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_stype');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_tmod', 'tss_aidev_upgrade_001', NULL, 'TARGETMODULE', '目标模块', 'varchar', NULL, 1, 64, '目标模块编码', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_tmod');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_intent', 'tss_aidev_upgrade_001', NULL, 'INTENT', '意图', 'text', NULL, 1, 0, '意图描述', 0, NULL, NULL, 7
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_intent');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_script', 'tss_aidev_upgrade_001', NULL, 'SCRIPTCONTENT', '脚本内容', 'text', NULL, 1, 0, '脚本内容', 0, NULL, NULL, 8
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_script');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_hash', 'tss_aidev_upgrade_001', NULL, 'SCRIPTHASH', '脚本哈希', 'varchar', NULL, 1, 64, '脚本哈希', 0, NULL, NULL, 9
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_hash');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_cnt', 'tss_aidev_upgrade_001', NULL, 'ITEMCOUNT', '项数量', 'int', NULL, 0, 11, '变更项数量', 0, NULL, '0', 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_cnt');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_status', 'tss_aidev_upgrade_001', NULL, 'STATUS', '状态', 'varchar', NULL, 0, 16, '状态', 0, NULL, 'PENDING', 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_status');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_eby', 'tss_aidev_upgrade_001', NULL, 'EXECUTEDBY', '执行人', 'varchar', NULL, 1, 36, '执行人ID', 0, NULL, NULL, 12
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_eby');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_etime', 'tss_aidev_upgrade_001', NULL, 'EXECUTEDTIME', '执行时间', 'datetime', NULL, 1, 0, '执行时间', 0, NULL, NULL, 13
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_etime');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_dur', 'tss_aidev_upgrade_001', NULL, 'DURATIONMS', '耗时', 'int', NULL, 1, 11, '执行时长毫秒', 0, NULL, NULL, 14
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_dur');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_err', 'tss_aidev_upgrade_001', NULL, 'ERRORMSG', '错误信息', 'text', NULL, 1, 0, '错误信息', 0, NULL, NULL, 15
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_err');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_rb', 'tss_aidev_upgrade_001', NULL, 'ROLLBACKSCRIPT', '回滚脚本', 'text', NULL, 1, 0, '回滚脚本', 0, NULL, NULL, 16
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_rb');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupg_isdel', 'tss_aidev_upgrade_001', NULL, 'ISDELETED', '是否删除', 'int', NULL, 0, 1, '是否删除', 0, NULL, '0', 17
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupg_isdel');

-- ============================================================
-- 6. tss_resfield — TSS_AIDEV_UPGRADE_LOG 字段 (11 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_id', 'tss_aidev_upgrade_log_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_uid', 'tss_aidev_upgrade_log_001', NULL, 'UPGRADEID', '升级ID', 'varchar', NULL, 0, 36, '升级记录ID', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_uid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_iid', 'tss_aidev_upgrade_log_001', NULL, 'ITEMID', '变更项ID', 'varchar', NULL, 1, 36, '变更项ID', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_iid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_icat', 'tss_aidev_upgrade_log_001', NULL, 'ITEMCATEGORY', '项类别', 'varchar', NULL, 1, 32, '项类别', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_icat');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_iact', 'tss_aidev_upgrade_log_001', NULL, 'ITEMACTION', '项操作', 'varchar', NULL, 1, 16, '项操作', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_iact');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_itgt', 'tss_aidev_upgrade_log_001', NULL, 'ITEMTARGET', '项目标', 'varchar', NULL, 1, 128, '项目标', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_itgt');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_sql', 'tss_aidev_upgrade_log_001', NULL, 'SQLSNIPPET', 'SQL片段', 'text', NULL, 1, 0, 'SQL片段', 0, NULL, NULL, 7
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_sql');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_status', 'tss_aidev_upgrade_log_001', NULL, 'STATUS', '状态', 'varchar', NULL, 1, 16, '状态', 0, NULL, NULL, 8
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_status');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_err', 'tss_aidev_upgrade_log_001', NULL, 'ERRORMSG', '错误信息', 'text', NULL, 1, 0, '错误信息', 0, NULL, NULL, 9
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_err');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_rows', 'tss_aidev_upgrade_log_001', NULL, 'ROWSAFFECTED', '影响行数', 'int', NULL, 1, 11, '影响行数', 0, NULL, NULL, 10
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_rows');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgl_etime', 'tss_aidev_upgrade_log_001', NULL, 'EXECUTEDTIME', '执行时间', 'datetime', NULL, 1, 0, '执行时间', 0, NULL, NULL, 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgl_etime');

-- ============================================================
-- 7. tss_resfield — TSS_AIDEV_UPGRADE_SNAPSHOT 字段 (6 字段)
-- ============================================================
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_id', 'tss_aidev_upgrade_snapshot_001', NULL, 'ID', '主键', 'varchar', NULL, 0, 36, '主键', 1, 'GUID', NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_id');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_uid', 'tss_aidev_upgrade_snapshot_001', NULL, 'UPGRADEID', '升级ID', 'varchar', NULL, 0, 36, '升级记录ID', 0, NULL, NULL, 2
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_uid');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_otype', 'tss_aidev_upgrade_snapshot_001', NULL, 'OBJECTTYPE', '对象类型', 'varchar', NULL, 1, 32, '对象类型', 0, NULL, NULL, 3
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_otype');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_oname', 'tss_aidev_upgrade_snapshot_001', NULL, 'OBJECTNAME', '对象名称', 'varchar', NULL, 1, 128, '对象名称', 0, NULL, NULL, 4
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_oname');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_before', 'tss_aidev_upgrade_snapshot_001', NULL, 'SNAPSHOTBEFORE', '变更前', 'text', NULL, 1, 0, '变更前快照', 0, NULL, NULL, 5
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_before');

INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, FIELDANAME, FIELDTYPE, PREC, NULLABLE, FIELDLENGTH, COMMENTS, ISKEY, KEYGENTYPE, DEFAULTVALUE, ENTRYNUM)
SELECT 'rf_aiupgs_after', 'tss_aidev_upgrade_snapshot_001', NULL, 'SNAPSHOTAFTER', '变更后', 'text', NULL, 1, 0, '变更后快照', 0, NULL, NULL, 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID = 'rf_aiupgs_after');
