-- ============================================================
-- 模块配置"接口脚本"入口 — 数据库升级
-- 内容: SS_MOD_CODEFILES(查模块关联的 C# 脚本+SQL 模板) + RS_M18 A06(APITYPE=sql)
-- 日期: 2026-07-17
-- 备注: 本接口本身就是 APITYPE=sql 脚本接口的自举应用(dogfooding)
--       NVelocity 铁律: 禁单引号(KIND 用 1/2 数字区分, LENGTH 判空)
-- ============================================================

-- 1. SQL 模板: 按模块查关联代码资产(C# 脚本 + SQL 模板)
INSERT INTO tss_sql (SQLID, SQLCODE, SQLTYPE, SQLTXT, REMARK)
SELECT 'sql_mod_codefiles', 'SS_MOD_CODEFILES', 'mysql',
'SELECT 1 AS KIND, S.ID AS RID, S.SCRIPTCODE AS CODE, S.SCRIPTNAME AS NAME, A.APICODE, A.APINAME
FROM tss_api_script S
LEFT JOIN tss_moudleapi A ON A.SCRIPTCODE=S.SCRIPTCODE AND A.MODULEID=(SELECT ID FROM tss_moudle WHERE MODULECODE=@MODULECODE)
WHERE S.ISDELETED=0 AND (A.ID IS NOT NULL OR S.SCRIPTCODE LIKE CONCAT(CHAR(83,67,95),@MODULECODE,CHAR(37)))
UNION ALL
SELECT 2 AS KIND, Q.SQLID AS RID, Q.SQLCODE AS CODE, Q.REMARK AS NAME, A.APICODE, A.APINAME
FROM tss_sql Q
LEFT JOIN tss_moudleapi A ON A.SQLID=Q.SQLCODE AND A.MODULEID=(SELECT ID FROM tss_moudle WHERE MODULECODE=@MODULECODE)
WHERE A.ID IS NOT NULL OR Q.SQLCODE LIKE CONCAT(CHAR(83,83,95),@MODULECODE,CHAR(37))
UNION ALL
SELECT 3 AS KIND, T.ID AS RID, T.MODULEPATH AS CODE, T.TEMPLATENAME AS NAME, T.FILETYPE AS APICODE, T.DESCRIPTION AS APINAME
FROM tbs_sfc_template T
WHERE T.ISDELETED=0 AND T.FILETYPE=CHAR(74,83) AND T.MODULEPATH LIKE CONCAT(CHAR(37),CHAR(47),CHAR(109,111,100,117,108,101,115,47),@MODULECODE,CHAR(37))
ORDER BY KIND, CODE', '模块关联的 C# 脚本与 SQL 模板(模块配置-接口脚本)'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_sql WHERE SQLCODE='SS_MOD_CODEFILES');

-- 2. RS_M18 A06 接口(APITYPE=sql, 脚本接口自举)
SET @m18 = (SELECT ID FROM tss_moudle WHERE MODULECODE='RS_M18');
INSERT INTO tss_moudleapi (ID, MODULEID, APICODE, ACTIONCODE, APITYPE, PATHNAME, APINAME, SQLID, ENTRYNUM)
SELECT 'ma_m18_a06', @m18, 'A06', 'codeFiles', 'sql', 'MAIN', '接口脚本', 'SS_MOD_CODEFILES', 6
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudleapi WHERE ID='ma_m18_a06');
