-- ============================================================
-- SS_MOD_CODEFILES 加 vue 组件 (KIND=4)
-- 模块开发中心代码编辑器左侧列表显示 Vue 组件文件
-- 日期: 2026-07-22
-- ============================================================

-- 重写 SS_MOD_CODEFILES: 加第四段 UNION 查 ASSETTYPE='vue' 的代码资产
-- KIND: 1=csharp, 2=sql, 3=js, 4=vue
-- vue 资产按 MODULEPATH 包含 /模块编码/ 过滤（与 js 过滤逻辑一致）
UPDATE tss_sql SET SQLTXT='SELECT 1 AS KIND, S.ID AS RID, S.CODE, S.NAME, S.MODULEPATH, A.APICODE, A.APINAME
FROM tss_code_asset S
LEFT JOIN tss_moudleapi A ON A.SCRIPTCODE=S.CODE AND A.MODULEID=(SELECT ID FROM tss_moudle WHERE MODULECODE=@MODULECODE)
WHERE S.ISDELETED=0 AND S.ASSETTYPE=CHAR(99,115,104,97,114,112) AND (A.ID IS NOT NULL OR S.CODE LIKE CONCAT(CHAR(83,67,95),@MODULECODE,CHAR(37)))
UNION ALL
SELECT 2 AS KIND, Q.ID AS RID, Q.CODE, Q.NAME, Q.MODULEPATH, A.APICODE, A.APINAME
FROM tss_code_asset Q
LEFT JOIN tss_moudleapi A ON A.SQLID=Q.CODE AND A.MODULEID=(SELECT ID FROM tss_moudle WHERE MODULECODE=@MODULECODE)
WHERE Q.ASSETTYPE=CHAR(115,113,108) AND (A.ID IS NOT NULL OR Q.CODE LIKE CONCAT(CHAR(83,83,95),@MODULECODE,CHAR(37)))
UNION ALL
SELECT 3 AS KIND, T.ID AS RID, T.CODE, T.NAME, T.MODULEPATH, T.FILETYPE AS APICODE, T.REMARK AS APINAME
FROM tss_code_asset T
WHERE T.ISDELETED=0 AND T.ASSETTYPE=CHAR(106,115) AND T.MODULEPATH LIKE CONCAT(CHAR(37),CHAR(47),CHAR(109,111,100,117,108,101,115,47),@MODULECODE,CHAR(37))
UNION ALL
SELECT 4 AS KIND, V.ID AS RID, V.CODE, V.NAME, V.MODULEPATH, NULL AS APICODE, NULL AS APINAME
FROM tss_code_asset V
WHERE V.ISDELETED=0 AND V.ASSETTYPE=CHAR(118,117,101) AND V.MODULEPATH LIKE CONCAT(CHAR(37),CHAR(47),@MODULECODE,CHAR(37))
ORDER BY KIND, CODE' WHERE SQLCODE='SS_MOD_CODEFILES';

-- 完成
