<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Realso.Data.DBAccess\Realso.Data.DBAccess.csproj" />
    <ProjectReference Include="..\Realso.Data.ORM.Core\Realso.Data.ORM.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="nvelocity" Version="1.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
