-- RS_M16 智能体提示词管理 元数据配置
-- 物理表 TBS_ASSISTANT_PROMPT 已建好

-- 1. 资源定义
-- 物理表
INSERT INTO tss_resource (ID, RESOURCENAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'tbs_ap_001', 'tbs_assistant_prompt', 'TBS_ASSISTANT_PROMPT', 'TABLE', NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID='tbs_ap_001');

-- DATAVIEW（前端列表/表单用）
INSERT INTO tss_resource (ID, RESOURCENAME, TABLENAME, RESOURCETYPE, TABLERESOURCEID)
SELECT 'vck_ap_001', 'vck_assistant_prompt', 'TBS_ASSISTANT_PROMPT', 'DATAVIEW', 'tbs_ap_001'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resource WHERE ID='vck_ap_001');

-- 2. 物理表字段定义（TBS_ASSISTANT_PROMPT）
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_id', 'tbs_ap_001', NULL, 'ID', 1, 'GUID' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_id');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_key', 'tbs_ap_001', NULL, 'PROMPTKEY', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_key');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_content', 'tbs_ap_001', NULL, 'CONTENT', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_content');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_desc', 'tbs_ap_001', NULL, 'DESCRIPTION', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_desc');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_updatedby', 'tbs_ap_001', NULL, 'UPDATEDBY', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_updatedby');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_updatetime', 'tbs_ap_001', NULL, 'UPDATETIME', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_updatetime');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_ap_isdeleted', 'tbs_ap_001', NULL, 'ISDELETED', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_ap_isdeleted');

-- 3. DATAVIEW 字段定义（REFFIELDID 关联物理表字段）
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_id', 'vck_ap_001', 'rf_ap_id', 'ID', 1, 'GUID' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_id');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_key', 'vck_ap_001', 'rf_ap_key', 'PROMPTKEY', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_key');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_content', 'vck_ap_001', 'rf_ap_content', 'CONTENT', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_content');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_desc', 'vck_ap_001', 'rf_ap_desc', 'DESCRIPTION', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_desc');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_updatedby', 'vck_ap_001', 'rf_ap_updatedby', 'UPDATEDBY', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_updatedby');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_updatetime', 'vck_ap_001', 'rf_ap_updatetime', 'UPDATETIME', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_updatetime');
INSERT INTO tss_resfield (ID, RESOURCEID, REFFIELDID, FIELDNAME, ISKEY, KEYGENTYPE)
SELECT 'rf_apv_isdeleted', 'vck_ap_001', 'rf_ap_isdeleted', 'ISDELETED', 0, NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfield WHERE ID='rf_apv_isdeleted');

-- 4. 过滤器
INSERT INTO tss_resfilter (ID, FILTERCODE, FILTERSQL, RESOURCEID, ORDERBY)
SELECT 'f_ap_f00', 'F00', 'A.PROMPTKEY=@PROMPTKEY', 'vck_ap_001', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfilter WHERE FILTERCODE='F00' AND RESOURCEID='vck_ap_001');
INSERT INTO tss_resfilter (ID, FILTERCODE, FILTERSQL, RESOURCEID, ORDERBY)
SELECT 'f_ap_f01', 'F01', '(A.PROMPTKEY LIKE CONCAT(''%'',@INPUT,''%'') OR A.DESCRIPTION LIKE CONCAT(''%'',@INPUT,''%''))', 'vck_ap_001', 'A.PROMPTKEY' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resfilter WHERE FILTERCODE='F01' AND RESOURCEID='vck_ap_001');

-- 5. 模块定义
INSERT INTO tss_moudle (ID, MODULECODE, MODULENAME, REMARK)
SELECT 'rs_m16_module_001', 'RS_M16', '提示词管理', '智能助理提示词配置'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudle WHERE MODULECODE='RS_M16');

-- 6. 数据源路径
INSERT INTO tss_moudlepath (ID, MODULEID, PATHNAME, RESOURCEID)
SELECT 'mp_ap16_main', 'rs_m16_module_001', 'MAIN', 'vck_ap_001'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudlepath WHERE MODULEID='rs_m16_module_001' AND PATHNAME='MAIN');
INSERT INTO tss_moudlepath (ID, MODULEID, PATHNAME, RESOURCEID)
SELECT 'mp_ap16_qry', 'rs_m16_module_001', 'QRY', 'vck_ap_001'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudlepath WHERE MODULEID='rs_m16_module_001' AND PATHNAME='QRY');
INSERT INTO tss_moudlepath (ID, MODULEID, PATHNAME, RESOURCEID)
SELECT 'mp_ap16_qqry', 'rs_m16_module_001', 'QQRY', 'vck_ap_001'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudlepath WHERE MODULEID='rs_m16_module_001' AND PATHNAME='QQRY');

-- 7. 接口定义
INSERT INTO tss_moudleapi (ID, MODULEID, APICODE, APITYPE, APINAME, FILTERCODE, PATHNAME, APIPARAM, BEFOREAPICODE, AFTERAPICODE)
SELECT 'ma_ap16_a01', 'rs_m16_module_001', 'A01', 'query', '查询', 'F01', 'QRY', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudleapi WHERE MODULEID='rs_m16_module_001' AND APICODE='A01');
INSERT INTO tss_moudleapi (ID, MODULEID, APICODE, APITYPE, APINAME, FILTERCODE, PATHNAME, APIPARAM, BEFOREAPICODE, AFTERAPICODE)
SELECT 'ma_ap16_a02', 'rs_m16_module_001', 'A02', 'open', '打开', 'F00', 'MAIN', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudleapi WHERE MODULEID='rs_m16_module_001' AND APICODE='A02');
INSERT INTO tss_moudleapi (ID, MODULEID, APICODE, APITYPE, APINAME, FILTERCODE, PATHNAME, APIPARAM, BEFOREAPICODE, AFTERAPICODE)
SELECT 'ma_ap16_a04', 'rs_m16_module_001', 'A04', 'save', '保存', NULL, 'MAIN', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudleapi WHERE MODULEID='rs_m16_module_001' AND APICODE='A04');
INSERT INTO tss_moudleapi (ID, MODULEID, APICODE, APITYPE, APINAME, FILTERCODE, PATHNAME, APIPARAM, BEFOREAPICODE, AFTERAPICODE)
SELECT 'ma_ap16_a07', 'rs_m16_module_001', 'A07', 'delete', '删除', NULL, 'MAIN', NULL, NULL, NULL
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_moudleapi WHERE MODULEID='rs_m16_module_001' AND APICODE='A07');

-- 8. UI 配置（resuipc）
INSERT INTO tss_resuipc (ID, RESOURCEID, RESFIELDID, FIELDNAME, LABELNAME, EDITTYPE, LISTSORT, QUERYSORT, EDITSORT, NULLABLE)
SELECT 'uipc_ap_key', 'vck_ap_001', 'rf_apv_key', 'PROMPTKEY', '提示词键', 'text', 1, 1, 1, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resuipc WHERE ID='uipc_ap_key');
INSERT INTO tss_resuipc (ID, RESOURCEID, RESFIELDID, FIELDNAME, LABELNAME, EDITTYPE, LISTSORT, QUERYSORT, EDITSORT, NULLABLE)
SELECT 'uipc_ap_desc', 'vck_ap_001', 'rf_apv_desc', 'DESCRIPTION', '说明', 'text', 2, 2, 2, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resuipc WHERE ID='uipc_ap_desc');
INSERT INTO tss_resuipc (ID, RESOURCEID, RESFIELDID, FIELDNAME, LABELNAME, EDITTYPE, LISTSORT, QUERYSORT, EDITSORT, NULLABLE)
SELECT 'uipc_ap_content', 'vck_ap_001', 'rf_apv_content', 'CONTENT', '提示词内容', 'textarea', NULL, NULL, 3, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resuipc WHERE ID='uipc_ap_content');
INSERT INTO tss_resuipc (ID, RESOURCEID, RESFIELDID, FIELDNAME, LABELNAME, EDITTYPE, LISTSORT, QUERYSORT, EDITSORT, NULLABLE)
SELECT 'uipc_ap_updatetime', 'vck_ap_001', 'rf_apv_updatetime', 'UPDATETIME', '更新时间', 'text', 3, NULL, NULL, 1
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resuipc WHERE ID='uipc_ap_updatetime');
INSERT INTO tss_resuipc (ID, RESOURCEID, RESFIELDID, FIELDNAME, LABELNAME, EDITTYPE, LISTSORT, QUERYSORT, EDITSORT, NULLABLE)
SELECT 'uipc_ap_id', 'vck_ap_001', 'rf_apv_id', 'ID', '#', 'index', NULL, NULL, NULL, 0
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_resuipc WHERE ID='uipc_ap_id');

-- 9. 菜单（系统管理下）
INSERT INTO tss_func (ID, FUNCCODE, FUNCNAME, FUNCTYPE, OUTERURL, UPFUNCID, FUNCICON, ISHIDE, ENTRYNUM)
SELECT 'rs_m16_func_001', 'RS_M16', '提示词管理', '2', 's01/m11', '1e38586dacef48559ddd565f9f79de59', 'h-icon-setting', 0, 11
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_func WHERE FUNCCODE='RS_M16');

-- 10. 功能点权限
INSERT INTO tss_funcpoint (ID, FUNCCODE, FUNCPOINTCODE, FUNCPOINTNAME, ENTRYNUM)
SELECT 'fp_ap16_query', 'RS_M16', 'A01', '查询', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_funcpoint WHERE FUNCCODE='RS_M16' AND FUNCPOINTCODE='A01');
INSERT INTO tss_funcpoint (ID, FUNCCODE, FUNCPOINTCODE, FUNCPOINTNAME, ENTRYNUM)
SELECT 'fp_ap16_save', 'RS_M16', 'A04', '保存', 2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_funcpoint WHERE FUNCCODE='RS_M16' AND FUNCPOINTCODE='A04');
INSERT INTO tss_funcpoint (ID, FUNCCODE, FUNCPOINTCODE, FUNCPOINTNAME, ENTRYNUM)
SELECT 'fp_ap16_del', 'RS_M16', 'A07', '删除', 3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM tss_funcpoint WHERE FUNCCODE='RS_M16' AND FUNCPOINTCODE='A07');
