<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="MySqlClient" Version="5.4.2" />
    <PackageReference Include="System.Data.OracleClient" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Realso.Utils\Realso.Utils.csproj" />
  </ItemGroup>

</Project>
