UPDATE TCK_ACCEPT
SET VER=VER+1,STATE =
CASE
WHEN @STATE IN (1,2,5)  THEN 13
WHEN @STATE IS NULL  THEN 13
WHEN @STATE = 6  THEN 9
END
WHERE ID = @REFBILLID AND STATE =
CASE
WHEN @STATE IN (1,2)  THEN 8
WHEN @STATE IS NULL  THEN 8
WHEN @STATE = 3  THEN 13
WHEN @STATE = 5  THEN 9
WHEN @STATE = 6  THEN 13
END
  OR
  STATE =
CASE
WHEN @STATE = 1  THEN 13
WHEN @STATE = 2  THEN 13
END;
CALL PSS_EXEC
('状态改变,请刷新后再试');

UPDATE TCK_ACCEPT
SET VER=VER+1,STATE = 8
WHERE  ID = @REFBILLID AND STATE=13;
CALL PSS_EXEC
('状态改变,请刷新后再试');

A.ID IN
(SELECT FUNCID
FROM TSS_ROLEFUNC
WHERE ROLEID IN(SELECT ROLEID
FROM TSS_USERROLE
WHERE USERID=@ID))



1=1
#if
("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date
(@BILLDATE_start,'%Y-%m-%d')
#end
#if
("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date
(@BILLDATE_end,'%Y-%m-%d')
#end
#if
("$!{CUSTNAME}"!="")
AND B.CUSTNAME LIKE CONCAT
('%',@CUSTNAME,'%')
#end
#if
("$!{BILLCODE}"!="")
AND A.BILLCODE LIKE CONCAT
('%',@BILLCODE,'%')
#end
#if
("$!{MNAME}"!="")
AND A.MNAME LIKE CONCAT
('%',@MNAME,'%')
#end
#if
("$!{EMPNAME}"!="")
AND D.EMPNAME LIKE CONCAT
('%',@EMPNAME,'%')
#end
#if
("$!{STATE}"!="")
AND A.STATE IN
(@STATE)
#end
#if
("$!{LINKER}"!="")
AND
(A.LINKER LIKE CONCAT
('%',@LINKER,'%') OR A.MOBILE LIKE CONCAT
('%',@LINKER,'%'))
#end
AND
((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR A.ADEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
)

1=1
#if
("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date
(@BILLDATE_start,'%Y-%m-%d')
#end
#if
("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date
(@BILLDATE_end,'%Y-%m-%d')
#end
#if
("$!{CUSTNAME}"!="")
AND D.CUSTNAME LIKE CONCAT
('%',@CUSTNAME,'%')
#end
#if
("$!{BILLCODE}"!="")
AND A.BILLCODE LIKE CONCAT
('%',@BILLCODE,'%')
#end
#if
("$!{MNAME}"!="")
AND A.MNAME LIKE CONCAT
('%',@MNAME,'%')
#end
#if
("$!{EMPNAME}"!="")
AND C.EMPNAME LIKE CONCAT
('%',@EMPNAME,'%')
#end
#if
("${STATE}"="1")
AND A.CHARGEID IS NULL
#end
#if
("${STATE}"="2")
AND A.CHARGEID IS NOT NULL
#end
#if
("$!{LINKER}"!="")
AND
(A.LINKER LIKE CONCAT
('%',@LINKER,'%') OR A.MOBILE LIKE CONCAT
('%',@LINKER,'%'))
#end
AND
((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR A.ADEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
)
{
	"resource": "/D:/gujing/work/项目/美云承接/gujing-mobile-business/discovery-web/",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "964",
	"severity": 8,
	"message": "The container 'Maven Dependencies' references non existing library 'C:\\Users\\ggtiger\\.m2\\repository\\com\\ctyun\\oos\\oos-sdk\\5.0.0\\oos-sdk-5.0.0.jar'",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

1=1
#if("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date(@BILLDATE_start,'%Y-%m-%d')
#end
#if("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date(@BILLDATE_end,'%Y-%m-%d')
#end
#if("$!{DOCNAME}"!="")
AND A.DOCNAME LIKE CONCAT('%',@DOCNAME,'%')
#end
#if("$!{DOCCODE}"!="")
AND A.DOCCODE LIKE CONCAT('%',@DOCCODE,'%')
#end
#if("$!{DOCSORT}"!="")
AND A.DOCSORT LIKE CONCAT('%',@DOCSORT,'%')
#end
#if("$!{DOCTYPEID}"!="")
AND A.DOCTYPEID = @DOCTYPEID
#end
#if("$!{DEPTNAME}"!="")
AND B.DEPTNAME LIKE CONCAT('%',@DEPTNAME,'%')
#end
#if("$!{CREATER}"!="")
AND A.CREATER LIKE CONCAT('%',@CREATER,'%')
#end
#if("$!{CHECKER}"!="")
AND A.CHECKER LIKE CONCAT('%',@CHECKER,'%')
#end
#if("$!{VERIFIER}"!="")
AND A.VERIFIER LIKE CONCAT('%',@VERIFIER,'%')
#end
#if("$!{STATE}"!="")
AND A.STATE IN(@STATE)
#end
AND ((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR A.DEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
)

UPDATE TCK_ACCEPT
SET VER=VER+1,STATE = 8
WHERE  ID = @REFBILLID AND  STATE=13;
CALL PSS_EXEC('状态改变,请刷新后再试');

UPDATE TCK_ACCEPT
SET VER=VER+1,STATE =
CASE
WHEN @STATE = 1  THEN 13
WHEN @STATE = 2  THEN 13
WHEN @STATE IS NULL  THEN 13
WHEN @STATE = 6  THEN 9
WHEN @STATE = 5  THEN 13
END
WHERE ID = @REFBILLID AND  (STATE =
CASE
WHEN @STATE = 1  THEN 8
WHEN @STATE = 2  THEN 8
WHEN @STATE IS NULL  THEN 8
WHEN @STATE = 3  THEN 13
WHEN @STATE = 5  THEN 9
WHEN @STATE = 6  THEN 13
END
 OR
 STATE =
CASE
WHEN @STATE = 1  THEN 13
WHEN @STATE = 2  THEN 13
END)
;
CALL PSS_EXEC('状态改变,请刷新后再试');


UPDATE TCK_ACCEPT
SET VER=VER+1,STATE =
CASE
WHEN @STATE = 1  THEN 13
WHEN @STATE = 2  THEN 13
WHEN @STATE IS NULL  THEN 13
WHEN @STATE = 6  THEN 9
WHEN @STATE = 5  THEN 13
END
WHERE ID = @REFBILLID AND  STATE =
CASE
WHEN @STATE = 1  THEN 8
WHEN @STATE = 2  THEN 8
WHEN @STATE IS NULL  THEN 8
WHEN @STATE = 3  THEN 13
WHEN @STATE = 5  THEN 9
WHEN @STATE = 6  THEN 13
END
 OR
 STATE =
CASE
WHEN @STATE = 1  THEN 13
WHEN @STATE = 2  THEN 13
END
;
CALL PSS_EXEC('状态改变,请刷新后再试1');


1=1
#if("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date(@BILLDATE_start,'%Y-%m-%d')
#end
#if("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date(@BILLDATE_end,'%Y-%m-%d')
#end
#if("$!{CUSTNAME}"!="")
AND D.CUSTNAME LIKE CONCAT('%',@CUSTNAME,'%')
#end
#if("$!{BILLCODE}"!="")
AND A.BILLCODE LIKE CONCAT('%',@BILLCODE,'%')
#end
#if("$!{MNAME}"!="")
AND A.MNAME LIKE CONCAT('%',@MNAME,'%')
#end
#if("$!{EMPNAME}"!="")
AND C.EMPNAME LIKE CONCAT('%',@EMPNAME,'%')
#end
#if("${STATE}"=="1")
AND A.CHARGEID IS NULL
#end
#if("${STATE}"=="3")
AND A.DISCOUNT < 1
#end
#if("${STATE}"=="2")
AND A.CHARGEID IS NOT NULL
#end
#if("$!{LINKER}"!="")
AND (A.LINKER LIKE CONCAT('%',@LINKER,'%') OR A.MOBILE LIKE CONCAT('%',@LINKER,'%'))
#end
AND ((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR A.ADEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
)

A.BILLDATE>(curdate() - 30)
AND
(A.BILLCODE LIKE CONCAT('%',@INPUT,'%')
OR B.CUSTNAME LIKE CONCAT('%',@INPUT,'%')
OR A.LINKER LIKE CONCAT('%',@INPUT,'%')
OR A.MOBILE LIKE CONCAT('%',@INPUT,'%')
OR A.MNAME LIKE CONCAT('%',@INPUT,'%')
OR A.SIZETYPE LIKE CONCAT('%',@INPUT,'%')
OR A.OPCODE LIKE CONCAT('%',@INPUT,'%')
OR A.MANUFACTURER LIKE CONCAT('%',@INPUT,'%')
OR A.CREATER LIKE CONCAT('%',@INPUT,'%')
OR E.DEPTNAME LIKE CONCAT('%',@INPUT,'%')
OR D.EMPNAME LIKE CONCAT('%',@INPUT,'%')
)
AND ((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR A.ADEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_) OR A.ADEPTID IS NULL
)

A.BILLDATE>(curdate() - 30)
AND
(A.REFBILLCODE LIKE CONCAT('%',@INPUT,'%')
OR A.CUSTNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCCODE LIKE CONCAT('%',@INPUT,'%')
OR A.CERTCODE LIKE CONCAT('%',@INPUT,'%')
OR A.OPCODE LIKE CONCAT('%',@INPUT,'%')
OR A.SIZETYPE LIKE CONCAT('%',@INPUT,'%')
OR A.MANUFACTURER LIKE CONCAT('%',@INPUT,'%')
OR A.CREATER LIKE CONCAT('%',@INPUT,'%')
OR A.CHECKER LIKE CONCAT('%',@INPUT,'%')
OR A.VERIFIER LIKE CONCAT('%',@INPUT,'%'))
AND ((SELECT COUNT(1)
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
=0 OR D.ADEPTID IN
(SELECT DEPTID
FROM TSS_USERDEPT
WHERE USERID=@_USERID_)
)


1=1
#if("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date(@BILLDATE_start,'%Y-%m-%d')
#end
#if("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date(@BILLDATE_end,'%Y-%m-%d')
#end
#if("$!{CUSTNAME}"!="")
AND A.CUSTNAME LIKE CONCAT('%',@CUSTNAME,'%')
#end
#if("$!{REFBILLCODE}"!="")
AND A.REFBILLCODE LIKE CONCAT('%',@REFBILLCODE,'%')
#end
#if("$!{CERTCODE}"!="")
AND A.CERTCODE LIKE CONCAT('%',@CERTCODE,'%')
#end
#if("$!{MNAME}"!="")
AND A.MNAME LIKE CONCAT('%',@MNAME,'%')
#end
#if("$!{CREATER}"!="")
AND A.CREATER LIKE CONCAT('%',@CREATER,'%')
#end
#if("$!{CHECKER}"!="")
AND A.CHECKER LIKE CONCAT('%',@CHECKER,'%')
#end
#if("$!{VERIFIER}"!="")
AND A.VERIFIER LIKE CONCAT('%',@VERIFIER,'%')
#end
#if("$!{EXPDATE_start}"!="")
AND A.EXPDATE>=str_to_date(@EXPDATE_start,'%Y-%m-%d')
#end
#if("$!{EXPDATE_end}"!="")
AND A.EXPDATE<=str_to_date(@EXPDATE_end,'%Y-%m-%d')
#end
#if("$!{STATE}"!="")
AND A.STATE IN(@STATE)
#end
AND A.VERIFYID=@_USERID_

(A.REFBILLCODE LIKE CONCAT('%',@INPUT,'%')
OR A.CUSTNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCCODE LIKE CONCAT('%',@INPUT,'%')
OR A.CERTCODE LIKE CONCAT('%',@INPUT,'%')
OR A.OPCODE LIKE CONCAT('%',@INPUT,'%')
OR A.SIZETYPE LIKE CONCAT('%',@INPUT,'%')
OR A.MANUFACTURER LIKE CONCAT('%',@INPUT,'%')
OR A.CREATER LIKE CONCAT('%',@INPUT,'%')
OR A.CHECKER LIKE CONCAT('%',@INPUT,'%')
OR A.VERIFIER LIKE CONCAT('%',@INPUT,'%'))
AND A.VERIFYID=@_USERID_



(A.DOCNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCCODE LIKE CONCAT('%',@INPUT,'%')
OR A.DEPTNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCSORT LIKE CONCAT('%',@INPUT,'%')
)
AND A.CHECKID=@_USERID_

(A.DOCNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCCODE LIKE CONCAT('%',@INPUT,'%')
OR A.DEPTNAME LIKE CONCAT('%',@INPUT,'%')
OR A.DOCSORT LIKE CONCAT('%',@INPUT,'%')
)
AND A.VERIFYID=@_USERID_


1=1
#if("$!{BILLDATE_start}"!="")
AND A.BILLDATE>=str_to_date(@BILLDATE_start,'%Y-%m-%d')
#end
#if("$!{BILLDATE_end}"!="")
AND A.BILLDATE<=str_to_date(@BILLDATE_end,'%Y-%m-%d')
#end
#if("$!{DOCNAME}"!="")
AND A.DOCNAME LIKE CONCAT('%',@DOCNAME,'%')
#end
#if("$!{DOCCODE}"!="")
AND A.DOCCODE LIKE CONCAT('%',@DOCCODE,'%')
#end
#if("$!{DOCSORT}"!="")
AND A.DOCSORT LIKE CONCAT('%',@DOCSORT,'%')
#end
#if("$!{DOCTYPEID}"!="")
AND A.DOCTYPEID = @DOCTYPEID
#end
#if("$!{DEPTNAME}"!="")
AND B.DEPTNAME LIKE CONCAT('%',@DEPTNAME,'%')
#end
#if("$!{CREATER}"!="")
AND A.CREATER LIKE CONCAT('%',@CREATER,'%')
#end
#if("$!{CHECKER}"!="")
AND A.CHECKER LIKE CONCAT('%',@CHECKER,'%')
#end
#if("$!{VERIFIER}"!="")
AND A.VERIFIER LIKE CONCAT('%',@VERIFIER,'%')
#end
#if("$!{STATE}"!="")
AND A.STATE IN(@STATE)
#end
AND A.VERIFYID=@_USERID_


(A.EMPCODE LIKE CONCAT('%',@INPUT,'%') OR A.EMPNAME LIKE CONCAT('%',@INPUT,'%'))
AND (
  A.DEPTID = @DEPTID
  OR
  (
   (SELECT COUNT(1) FROM TSS_USERDEPT TTT WHERE TTT.DEPTID=@DEPTID AND TTT.USERID IN (SELECT ID FROM TSS_USER TT WHERE A.ID = TT.EMPID))>0
  )
)
AND (SELECT COUNT(1) FROM TSS_USERROLE AA,TSS_ROLE BB,TSS_ROLEFUNC CC WHERE  AA.ROLEID = BB.ID AND BB.ID = CC.ROLEID
AND CC.FUNCID =@FUNCID AND AA.USERID IN (SELECT ID FROM TSS_USER TT WHERE A.ID = TT.EMPID))>0
